### ISSUE TITLE
Going from use_ssl == true to use_ssl == false; config.json still has ssl config info in it

### ISSUE THREAD

**Issue by rberger** [sensu/sensu-chef#182]
If you run chef-client and have use_ssl true and then later set use_ssl false, the sensu_client config.json continues to have 

```
    "ssl": {
      "cert_chain_file": "/etc/sensu/ssl/cert.pem",
      "private_key_file": "/etc/sensu/ssl/key.pem"
    },
```

in the rabbitmq section. It does set the port to the non-ssl port number, but the ssl cert files and the ssl key is still there.

It seems that if the ssl key with values is in the file, it still has the client try to use ssl which of course doesn't work.

I spent an entire evening trying to modify sensu_chef::default as well as a wrapper cookbook to delete or set to nil or {} the node.sensu.rabbitmq.ssl attribute.

Even tried some suggestions by Portertech from IRC and no matter what I did I couldn't get rid of the ssl key or values.

Now its possible it was due to lack of sleep, but I really tried.

The most complicate attempt was the one suggested by Portertech:

```
node.force_override['sensu']['rabbitmq'] = node.sensu.rabbitmq.to_hash.reject {|k,v| k == 'ssl'}
```

But also tried:

```
node.override['sensu']['rabbitmq']['ssl'] = nil
node.override['sensu']['rabbitmq']['ssl'] = {}
```

This shouldn't be so hard. 

Am I doing something stupid? Or is this really an issue?

Thanks,
Rob

**Comment by bkett** [comment]
Just tested this today post-merge of the 12.04 ssl fix, this issue didn't occur.

**Comment by portertech** [comment]
Closing this issue.
