### ISSUE TITLE
Sensu::Helpers.random_password does not meet password complexity requirements

### ISSUE THREAD

**Issue by rtacconi** [sensu/sensu-chef#249]
ArgumentError
-------------
The password does not meet the password policy requirements. Check the minimum p
assword length, password complexity and password history requirements.

Resource Declaration:
---------------------
# In c:/chef/cache/cookbooks/sensu/recipes/_windows.rb

 22: user "sensu" do
 23:   password Sensu::Helpers.random_password
 24: end
 25:

**Comment by rjbez17** [comment]
I created a pull request to fix this: https://github.com/sensu/sensu-chef/pull/319

**Comment by portertech** [comment]
Thanks to #319, this should no longer be an issue.
