### ISSUE TITLE
apt-get upgrade breaks the Sensu recipe

### ISSUE THREAD

**Issue by rosenfeld** [sensu/sensu-chef#255]
```
apt-cache policy rabbitmq-server 
rabbitmq-server:
  Installed: 3.1.5-1
  Candidate: 3.2.4-1
  Version table:
     3.2.4-1 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
 *** 3.1.5-1 0
        100 /var/lib/dpkg/status
```

That means that upgrading my server will break my Chef recipe since it requires a specific version (3.1.5) which fails to be downgraded after 3.2.4 is installed by `apt-get upgrade`.

If this recipe depends on this specific `rabbitmq-server` package version it should also set the proper pin settings to prevent `apt-get upgrade` to try to upgrade the rabbitmq-server package.

**Comment by bkett** [comment]
I am pretty sure this issue doesn't exist anymore, the cookbook installs the latest version of rabbitmq.

**Comment by rosenfeld** [comment]
I don't agree. They still specify the version:

https://github.com/jjasghar/rabbitmq/blob/master/attributes/default.rb#L2

It doesn't matter whether the current version is the latest or not. At some point a new release will be available and the recipe will break the `apt-get upgrade`. They should either stop specifying the version or hold the version.

**Comment by bkett** [comment]
@rosenfeld But given that this cookbook is meant to be used in a wrapper pattern, couldn't you just override that attribute? Also, even if the attribute is taken out from this cookbook the rabbitmq cookbook which this one depends on also sets a default version and so you'd still get this behavior.

**Comment by rosenfeld** [comment]
How do you override it to not use a version at all? And if you manage to do so, how can you make sure that new released versions will be compatible with the templates used in the rabbitmq cookbook? What makes more sense to me is to fix the version but also configure apt to not upgrade that package, just like what I suggested in the PR I sent them a long time ago...

**Comment by rosenfeld** [comment]
What I mean is that the rabbitmq cookbook is currently broken. I'm not sure what is the best way to handle with it. Should the Sensu community maintain a fork of the rabbitmq cookbook with the fix? Or should they try to convince the rabbitmq cookbook developers to accept the suggested patch? Or should Sensu developers manage rabbitmq installation in the Sensu recipes themselves and stop using the rabbitmq cookbook? I'm not sure what is the best way to handle this problem, but pretending it doesn't exist doesn't help either...

**Comment by bkett** [comment]
@rosenfeld Yep I get what you're saying now. I'm not sure what the right call is either. Ideally the responsibility would fall on the rabbitmq cookbook maintainers and either accept the patch or for whatever reason refuse to accept it. I'm pretty against trying to maintain a fork of that cookbook with this patch merged in because who knows how often it'd get updated with changes from the upstream, and reimplementing the installation recipe doesn't seem ideal either...not many good options :(

**Comment by rosenfeld** [comment]
The reason why they rejected it is because I only handled the Debian/Ubuntu case (apt) while they also support RedHat and I'm not interested in learning how to fix it for RedHat and I don't agree that this should be required for them to accept the fix. They also complained that I didn't write a test for it and since I also don't agree with enforcing someone to write a test for it for accepting bug fixes I also decided to not try to learn about Chefspec. I have both no interest and time to work on such a test for a single line change that fixes the problem... If someone is willing to work on the RedHat support or writing the missing test that would be another option as well...

**Comment by rosenfeld** [comment]
Another option might be switching the default setting for `use_distro_version`:

`default.rabbitmq.use_distro_version = true`

If `sensu` enables it by default then it won't break `apt-get upgrade`. That's what I did for our recipes for example.

**Comment by bkett** [comment]
@rosenfeld I just tested this with the latest version of the cookbook and couldn't reproduce; could be coincidental that the versions are equal or something.

**Comment by rosenfeld** [comment]
Please read my comment from 5 days ago starting with "I don't agree". I'm on the phone and it's hard to retype it here

**Comment by bkett** [comment]
@rosenfeld that's why I said it could be coincidental that it works currently. I'll retest in my fork by setting the attribute to some earlier version of rabbitmq.

**Comment by rosenfeld** [comment]
It won't always cause troubles because sometimes the previous version will be compatible and the downgrade will be possible, but this is not the only problem that could happen. Another problem is that for a new release to come up and the current settings format could be invalid for the new version. Ideally the recipe should fix the version but it should also fix it in the package manager...

**Comment by luckymike** [comment]
@rosenfeld it looks like this is resolved in the rabbitmq cookbook, the version is only set when you set `pin_distro_veresion` to `true`: https://github.com/jjasghar/rabbitmq/blob/master/recipes/default.rb#L56

**Comment by rosenfeld** [comment]
It doesn't really fix anything. Specifying the version doesn't set the pin options which won't prevent the package from being upgraded. Nothing changed from the initial scenario that led to this issue. Simply closing it without understanding does not sound much productive just because some open ticket is bothering you while the issue still exists... Pretending it doesn't exist won't really fix it...

**Comment by luckymike** [comment]
@rosenfeld:

1) We do not maintain the rabbitmq cookbook. That's where the version is set (and where it can be disabled), so this cookbook is not the appropriate venue to address this, frustrations with a rejected pull request not-withstanding.  

2) The attribute that you're concerned with is only applied if another attribute is set to `true`, in other words, you have complete control to either manage the version or disable the versioning entirely.

This cookbook is meant to support your own scenario-specific wrapper cookbook. From the README:
>This cookbook provides the building blocks for creating a monitoring cookbook specific to your environment (wrapper). Without such a wrapper, no Sensu configuration files will be created for your nodes.

Attributes and the behavior they trigger can change at any time based on the whims of the maintainers. We're far more likely to introduce future issues by arbitrarily adjusting other cookbooks' attributes than we are to resolve them. The best we can do is provide a reasonable working framework that is flexible enough that you may adjust it in your wrapper. That is the reason we do not consider this a valid issue for this cookbook, not because we're ignoring the scenario you've presented.

**Comment by rosenfeld** [comment]
Hi @luckymike,

1) I understand you don't maintain the rabbitmq cookbook, but you do maintain the Sensu recipe and it should work regardless of other cookbooks you don't maintain. We should figure out some solution despite the inability of convincing rabbitmq cookbook maintainers to fix on their side and forking it is not the only possible fix.

2) You seem to have missed what the issue is all about as you think that simply not setting the version of rabbitmq is a robust enough solution while it's not.

Let me give you an example using one of the gems that I maintain:

https://github.com/rosenfeld/active_record_migrations

Specifically this part:

https://github.com/rosenfeld/active_record_migrations/blob/master/active_record_migrations.gemspec#L23-L30

The comments refer to this file:

https://github.com/rosenfeld/active_record_migrations/blob/master/lib/active_record_migrations/generators/migration.rb

Basically, there's a long standing bug in ActiveRecord that allows you to change the paths on where to look for migrations but new migrations are created in a hard-coded path. Due to this my only option to allow changing that path was by kind of monkey patching AR even if I couldn't convince them to accept my pull requests. Because it's my gem's responsibility to ensure it works. But since it monkey patches an specific implementation of some small method I can't specify a loose version dependency, even though that method has never changed since AR 4.0.0. It would be much simpler to just maintain the optimistic version, which assumes this method implementation won't change:

https://github.com/rosenfeld/active_record_migrations/tree/optimistic

If you take a look at my commits in the project they are only changing the dependencies in AR after I check that implementation of that method hasn't changed. This is certainly more work, but it's the right solution in my opinion until AR fixes this in their side but this is out of my control while maintaining that gem is still my responsability.

In the case of Sensu, it relies on RabbitMQ but it may no longer work when RabbitMQ is upgraded because some configuration is no longer valid or if they changed their client usage or supported features, API and so on. Once you test with a newer version you can be sure it still works and then you could fix the dependency in a newer version of RabbitMQ. So, in my opinion, the right strategy is to fix the version of RabbitMQ to a known one, but we should do it properly by setting the pin version correctly so that `apt-get upgrade` won't touch it.

It's my opinion that the right fix would be to allow the RabbitMQ version to be unspecified but to specify it by default (like I offer the optimistic version of active_record_migrations but it's not the default one) and fix its version properly by default and set its pin version in this recipe until this is fixed in rabbitmq own recipe, like I do in active_record_migrations.

Imagine the follow common scenario. You perform an `apt-get upgrade` in your server as usual and then suddenly Sensu stops working. Then you realize that upgrading rabbitmq during the upgrade broke Sensu. And you realize that downgrading rabbitmq is no longer possible, either because the previous version is no longer available in the repository or because the downgrade procedure does not work. In the last case you have the option to uninstall it and reinstall the old version but for the former there's actually no real option. That means that the monitoring server will stop working after the upgrade and will remain not working until the Sensu recipe is fixed to work with the latest rabbitmq and the recipe is upgraded causing lots of uneeded headaches to the server admin who just upgraded the server... This is a situation that could be easily avoided by simply specifying the dependencies versions and setting the pin version.

Closing this issue is the same as pretend the issue no longer exists, which is not true.

**Comment by luckymike** [comment]
@rosenfeld If you set the RabbitMQ version via the supplied attribute in your wrapper cookbook (`node['rabbitmq']['version']`), Chef will not upgrade RabbitMQ regardless of future changes to the RabbitMQ cookbook (which you may also pin pessimistically if you're concerned the behavior may change).

`apt-get upgrade` is not something I would consider wise or safe to run on a Chef managed node, as that will apply a host of package updates blindly and out of band of your configuration management. Cookbook logic won't impact `apt-get upgrade` run manually on a system.

**Comment by rosenfeld** [comment]
Well, in that case then there's really a mismatch on what you and I think about best practices. `apt-get upgrade` is expected to be run now and then in every server which is actively maintained to keep the server updated with fixes for security holes and other enhancements. I maintain our servers this way and manage all of them with Chef and this strategy works fine once you understand that sometimes setting the pin versions is the way to go for this to work. But if you bet that most servers shouldn't be 'apt-get upgrade'ed when managed by Chef, then I have no other arguments to discuss here... :(

**Comment by luckymike** [comment]
I should have been more specific. I would not run `apt-get upgrade` on a Chef node without:
a) using private package repos with a curated set of versions
b) specifying specific packages to upgrade
c) pinning specific versions via the apt configuration

You can pin packages for safe use of `apt-get upgrade` via your wrapper cookbook. That is well outside the scope of this cookbook, and the version pinning you've suggested would only apply to the package resource install action, not an `apt-get upgrade` performed manually/via cron/etc.

**Comment by luckymike** [comment]
Here's the LWRP you could use: 
https://github.com/chef-cookbooks/apt/blob/master/resources/preference.rb

**Comment by rosenfeld** [comment]
In the hypothesis that running `apt-get upgrade` regularly is a common practice even when the servers are managed by Chef, which you seem to disagree, then it would be this recipe's responsibility to take care of which rabbitmq (and any other dependencies) versions this recipe was tested against and pinning it by default so that another recipe using this one wouldn't have to worry about this kind of thing. But this is a matter of understanding what are common practices and what each piece is responsible for. This is how I see things but of course you are free to disagree. I was just insisting because I thought you would agree that `apt-get upgrade`  should be expected and is a common operation but if you don't think that is the case then I have no way to try to convince you that the issue still exists. That's fine, but maybe mentioning that the dependencies versions are not pinned in the end of the README could save some time for other people with a different set of opinions. Maybe some note like:

"this recipe does not fix the versions of our dependencies, like rabbitmq, so if you are afraid of Sensu breaking after some manual `apt-get upgrade` due to incompatibilities and if you run such command manually sometimes, maybe you should consider pinning the versions of the following dependencies in your own recipes: ..."

**Comment by luckymike** [comment]
How's this? 
https://github.com/sensu/sensu-chef/pull/400/files

**Comment by rosenfeld** [comment]
"This cookbook either pins its dependencies optimistically"

What does optimistic dependency pinning mean?

**Comment by rosenfeld** [comment]
My understanding of pinning is that it's the opposite of optimistic versioning and, in the case of this recipe, being optimistic means not setting any versions at all, right?

**Comment by luckymike** [comment]
I use "pinning" to refer to any constraint. We we `>=` for a number of the dependent cookbooks, which is an optimistic pin, but I can change that for clarity.

**Comment by rosenfeld** [comment]
Ah, I see, I'd just refer to that as optimistic versioning as pinning has an strict meaning in Debian packages terminology.

**Comment by luckymike** [comment]
Updated

**Comment by rosenfeld** [comment]
Looks good, thanks
