### ISSUE TITLE
sensu_gem does not install sensu-plugin.rb gem

### ISSUE THREAD

**Issue by kmejka** [sensu/sensu-chef#261]
Am I using this wrong?
After installing sensu with LWRP sensu_gem, like so:

    sensu_gem "rest-client"
or

    sensu_gem "sensu-plugin" do
        version node["monitor"]["sensu_plugin_version"]
    end

I can see these gems in the folder

    /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems
But it is not found using 
    
     gem list
and in my checks I keep getting errors about missing gms

    {"timestamp":"2014-06-10T07:53:49.062045+0000","level":"info","message":"publishing check result",
    "payload":{"client":"precise32","check":{"type":"metric","command":"rabbitmq-overview-metrics.rb",
    "handlers":["metrics"],"standalone":true,"interval":30,
    "name":"rabbitmq_overview_metrics","issued":1402386829,
    "executed":1402386829,
    "output":"/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': 
    cannot load such file -- sensu-plugin/metric/cli (LoadError)\n\tfrom /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'\n\tfrom /etc/sensu/plugins/rabbitmq-overview-metrics.rb:36:in `<main>'\n","status":1,"duration":0.039}}}

Without manually installing these gems my sensu checks don't work.

I use the default sensu cookbook installation parameters regarding embedded ruby:

     override["sensu"]["use_embedded_ruby"] = false

**Comment by pmvilaca** [comment]
@kmejka There was an issue with the gemspec of the plugins. The binstubs weren't being created under /opt/sensu/embedded/bin/ , so that was the reason for the failures that we saw in the log. If you update the gems that you're using to version 0.0.2, you'll see that the plugins will be available on that location.

As that location is being added to the path if embedded ruby is used, it'll work.

**Comment by cwjohnston** [comment]
In addition to the binstub issues mentioned above, sensu packages now default `EMBEDDED_RUBY` to `true` (as of sensu version 0.21), which should alleviate confusion around this issue. If you are still having problems. please feel free to open a new issue.
