### ISSUE TITLE
These dependency constraints are dumb

### ISSUE THREAD

**Issue by mconigliaro** [sensu/sensu-chef#272]
Don't do this:

`depends "redisio", ">= 1.7.0"``

This will blow up when redisio releases a breaking change (e.g. version 2.0). 

Do this instead:

`depends "redisio", "~> 1.7"``

Now you'll get all the non-breaking updates in the 1.x series, but you won't get bit by breaking changes, or this bug that was apparently just introduced in the 2.0 series:
```
SyntaxError
       -----------
       /tmp/kitchen/cookbooks/redisio/providers/PaxHeader/configure.rb:1: syntax error, unexpected tIDENTIFIER, expecting $end
       16 gid=72107521
```

**Comment by cwjohnston** [comment]
Per the readme:
```
This cookbook provides the building blocks for creating a monitoring cookbook specific to your environment (wrapper). 
```

Closing this issue with the suggestion that the major version should be pinned in your wrapper cookbook.
