### ISSUE TITLE
too restrictive directory permissions

### ISSUE THREAD

**Issue by petere** [sensu/sensu-chef#274]
I find that setting the permissions of directories such as `/etc/sensu/` and subdirectories as well as `/var/log/sensu/` to 0750 to be too restrictive and impractical.  The effect is that a lot of debugging ends up happening as root, which isn't good.  I see reasons for keeping the contents of (some) files not readable by everyone, but hiding the existence of files doesn't seem useful.  What is the reason for this?  Could this be changed?  Should an attribute be added to be able to override this?

**Comment by cwjohnston** [comment]
Closing this issue as related PR was previously closed without merging.
