### ISSUE TITLE
Add ignore_failure attribute to service resources

### ISSUE THREAD

**Issue by boldfield** [sensu/sensu-chef#296]
We run sensu, redis and rabbitmq on seperate nodes, all of them running sensu-client.  This leads to circular dependencies between nodes and failed node bootstraps when trying to create a new environment, e.g. a chef bootstrap run on a rabbitmq node will fail because sensu-client can't connect to services it depends on.  I propose that ```ignore_failure``` and a node attribute ```node.sensu.ignore_start_failure``` (defaulted to ```false``` to maintain current behavior) be utilized to facilitate use cases like ours.

Pull request to follow.

**Comment by cwjohnston** [comment]
Closing this issue and related (unmergable) PR as `sensu-client` no longer fails to start when transport is unavailable.
