### ISSUE TITLE
sensu_gem cannot install gem

### ISSUE THREAD

**Issue by akerekes** [sensu/sensu-chef#298]
I'm using a fairly old version of the cookbook (1.0.0) but cannot upgrade now. Since this Monday my nodes cannot converge, because I get the following error message:

       [2014-12-01T23:46:54+00:00] ERROR: gem_package[redis] (/tmp/kitchen/cache/cookbooks/sensu/providers/gem.rb line 2) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
       ---- Begin output of /opt/sensu/embedded/bin/gem install redis -q --no-rdoc --no-ri -v "3.1.0" ----
       STDOUT: 
       STDERR: ERROR:  Could not find a valid gem 'redis' (= 3.1.0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)
       ---- End output of /opt/sensu/embedded/bin/gem install redis -q --no-rdoc --no-ri -v "3.1.0" ----
       Ran /opt/sensu/embedded/bin/gem install redis -q --no-rdoc --no-ri -v "3.1.0" returned 2

This cookbook was running without issues last Wednesday, but not today.
What has changed?

**Comment by neurogenesis** [comment]
while a problem with rubygems & openssl & root certificates for AddTrust / COMODO, it will also become a problem for embedded ruby installs (which aren't updated with package managers or system ruby installs). was this fixed in a new release of the sensu chef cookbook?
