### ISSUE TITLE
More flexible data bag configuration desirable

### ISSUE THREAD

**Issue by aaduffy** [sensu/sensu-chef#306]
The implementation choice in Sensu::Helpers.data_bag_item which forces the use of a specific 'sensu' data bag with specific items makes the sensu-chef cookbook inflexible for larger implementations (https://github.com/sensu/sensu-chef/blob/master/libraries/sensu_helpers.rb#L39). A common Chef pattern is to use different data bags for different environments or to use namespacing of data bag items to differentiate configuration per environment. It would be helpful to permit a mechanism to override the default data_bag_item implementation, possibly using an attribute or set of attributes to control the feature.

The Issue
--------------
Presently SSL configuration must be in the data bag 'sensu' under the item 'ssl'. When working with multiple deployments within the same Chef organization this causes all deployments to use the exact same SSL certificates everywhere. This is problematic in environments that require compartmentalization of different customer systems or different environments for development, test, and production.
This problem is not restricted to the 'ssl' item. The 'config' item suffers the same shortcoming.

Proposed Solutions
--------------------------
1) Allow per-item override of data bag items
This is a very simplistic but effective solution. In data_bag_item check for node['sensu']['data_bag_item'][item]. If it is defined use its content instead of the content in the 'sensu' data bag. This would allow implementors to do their own data bag processing and wholesale substitute the 'ssl' and 'config' items per environment.
2) Allow substitution of the data bag to use
Instead of hard-coding 'sensu' as the name of the data bag, define it as a default attribute (eg. default['sensu']['data_bag'] = 'sensu'). This could be overridden in environments that care to use a different data bag.
3) Permit registration of an options 'data_bag_item' implementation
The exact logic of this proposal is unclear to me but it would essentially entail addition of logic to data_bag_implementation that would call a implementor-defined method instead of running the default logic if the implementor-defined method exists.

**Comment by pghalliday** [comment]
I would suggest that the simplest solution would be to:

4) not use data bags at all and only use attributes. Leave it up to end users to decide where to get the SSL certs from and they can set the attributes at run time

Is there any reason to keep the use of data bags in this recipe?

**Comment by pghalliday** [comment]
An alternative to attributes could be to implement an LWRP for setting the certs. This has the advantage that it's attributes will not get listed under the node in the chef server. It is a problem that you can encrypt a data bag but when you load it and pull out values to override attributes, those attributes are then visible as plain text in the chef server, LWRPs don't suffer from this issue (unless they also override attributes)

**Comment by pghalliday** [comment]
I just came across another appoach:

http://lists.opscode.com/sympa/arc/chef/2014-08/msg00028.html

The `node.run_state` can be used to set run time parameters that will not be persisted back to the chef server. Sounds promising and is used in the community Jenkins recipe

**Comment by cwjohnston** [comment]
I think an LWRP which populates `node.run_state` with the required
credentials may be a good idea. I have used the run state for similar
purposes in other projects and it generally works well.

**Comment by pghalliday** [comment]
@cwjohnston not sure what the LWRP adds in that scenario

**Comment by cwjohnston** [comment]
@pghalliday @aaduffy It would be great to get some feedback on #410 as a solution to this issue. Thanks!

**Comment by cwjohnston** [comment]
Resolved in #410 which will be released in upcoming version 2.12.0. Thanks!
