### ISSUE TITLE
The stash expire option does not work

### ISSUE THREAD

**Issue by willejs** [sensu/sensu-chef#308]
The stash provider calls the stash(?:es) endpoint with the resource name in the path which does not set the redis key ttl of the stash.

However if you call the [stashes/?](https://github.com/sensu/sensu/blob/master/lib/sensu/api.rb#L681) endpoint evaluates the payload and matches the expires key and sets the ttl. 

We should patch the cookbook to use the stashes endpoint instead of the stash endpoint?

**Comment by Igorshp** [comment]
https://github.com/sensu/sensu-chef/pull/309

**Comment by Igorshp** [comment]
@willejs @portertech this issue can be closed now?
