### ISSUE TITLE
RabbitMQ is not configured to verify TLS certificates

### ISSUE THREAD

**Issue by orion-raft** [sensu/sensu-chef#315]
Here is a snippet of the rabbitmq config file generated by this cookbook:

```
    {ssl_options, [{cacertfile,"/etc/rabbitmq/ssl/cacert.pem"},
                    {certfile,"/etc/rabbitmq/ssl/cert.pem"},
                    {keyfile,"/etc/rabbitmq/ssl/key.pem"},
                    {verify,verify_none},
                    {fail_if_no_peer_cert,false}]},
```
`verify_none` should be `verify_peer`.

See also:
https://github.com/jjasghar/rabbitmq/blob/master/attributes/default.rb#L57

**Comment by runningman84** [comment]
+1

**Comment by portertech** [comment]
The RabbitMQ cookbook changed the default. Will adjust.

**Comment by cwjohnston** [comment]
Appears this is fixed as of https://github.com/sensu/sensu-chef/commit/7f1ee132bdbd66c9b4647a3f07723bab35af8c9f
