### ISSUE TITLE
new attributes not defined for windows clients

### ISSUE THREAD

**Issue by jhsubscribe** [sensu/sensu-chef#318]
A couple of recent commits ( c33fabe7cd03239b93d6410b05dfed68be64cd8e ) have included attributes (e.g. user, group, log_directory etc) that are only set for Linux clients which leads to compilation errors on windows clients that are dependent on this cookbook.

e.g. Undefined method or attribute `directory_mode' on `node'

As a workaround I'm just defining them in my wrapper cookbook but I expect the default attributes.rb just needs updating so that any attribute defined on linux is defined on windows (even if not used).  

ps. Apologies for doing this as an issue rather than a PR - I need to learn how to do those.
pps. Thanks all for work on this cookbook.  Really useful

Thanks, 
James

**Comment by portertech** [comment]
@jhsubscribe Thank you for reporting :+1: Here's the fix https://github.com/sensu/sensu-chef/pull/321
