### ISSUE TITLE
Chef definitions do not support not_if/only_if

### ISSUE THREAD

**Issue by Igorshp** [sensu/sensu-chef#322]
Just been bitten by the above issue:

```
 sensu_silence_client "#{node.name}" do
    api_uri api_uri
    expire 300
    not_if { node['monitor_cookbook'].attribute?("run_once")
 end
```
it's a known issue as it turns out: https://tickets.opscode.com/browse/CHEF-778
Chef definitions are compiled at recipe compile time and do not evaluate not_if/only_if

The workaround is to simply wrap it in an if statement, but it's messy.

Do you think it's worth reimplementing stash definitions as a provider?

**Comment by cwjohnston** [comment]
Closing due to age of issue and lack of updates. If you'd like to submit a PR for this change we will be happy to review it!
