### ISSUE TITLE
Don't force use of data bag for SSL

### ISSUE THREAD

**Issue by dblessing** [sensu/sensu-chef#325]
Please don't force the use of a data bag for SSL. We use Chef Vault and have a mechanism for distributing certs to nodes. We only need to point Sensu at the filesystem path.

**Comment by acqant** [comment]
+1

**Comment by Entr04y** [comment]
Same for us.  We use AWS and data bag usage is very limited within opsworks.

**Comment by pghalliday** [comment]
+1

**Comment by agutierrezl** [comment]
+1000

**Comment by cwjohnston** [comment]
Duplicates #306

**Comment by jeremysmitherman** [comment]
+1

**Comment by cwjohnston** [comment]
It would be great to get some feedback on #410 from those who have +1'd this issue. Thanks!

**Comment by elnica6** [comment]
+1 on #410. This would fit the bill for us to allow for an AWS autoscaled solution

**Comment by cwjohnston** [comment]
Resolved in #410 which will be released in upcoming version 2.12.0. Thanks!
