### ISSUE TITLE
Promote occurrences to first-class check attribute

### ISSUE THREAD

**Issue by jhmartin** [sensu/sensu-chef#328]
'occurrences' is a defacto standard option for checks; please consider promoting it out of something that has to be added as an additional attribute into the same level as 'interval'.

**Comment by cwjohnston** [comment]
We'll consider this for a future enhancement

**Comment by cwjohnston** [comment]
Although `occurrences`used by many, it's not currently one of the attributes defined in the [check result specification](https://sensuapp.org/docs/latest/reference/checks.html#check-result-specification). 

Until such time as it is added to the check result specification, I'm 👎  on treating `occurrences` as a first-class attribute of `sensu_check` resources.
