### ISSUE TITLE
Chef cookbook sets Embedded to false, as a default.

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu-chef#335]
It might be handy for new adopters of the Sensu cookbook that  /etc/default/sensu  sets the embedded variable to false by default (matching the standard rpm default).

Side subject:  Do most people using Sensu manage their own ruby install, or just use the omnibus version?  Would be interesting if there's data around that.

Created pull request with this small documentation change:  https://github.com/sensu/sensu-chef/pull/334

**Comment by runningman84** [comment]
I like the embedded ruby. This allows us to have three rubys without conflicts.

* sensu ruby
* chef ruby
* system ruby

**Comment by scalp42** [comment]
@runningman84 @xyntrix the danger is that if you install sensu gems for the embedded, you could break sensu from running itself if I'm correct.

**Comment by cwjohnston** [comment]
Given that Sensu 0.21 now defaults `EMBEDDED_RUBY` to `true`, I think this cookbook default attribute needs to change as well. We'll consider this for a future enhancement.

**Comment by majormoses** [comment]
+1 for embedded ruby to default of true for the reasons outlined above regarding ruby namespacing. Additionally as pointed out about the change as of 0.21 the cookbook should mirror the sensu defaults and recommended configuration.

**Comment by luckymike** [comment]
:+1: for `true`
I'm torn on whether or not this merits a major version bump. On the one hand, by flipping that we're maintaining the default behavior of the sensu package (e.g. non-breaking in terms of intent), on the other hand, we're switching the cookbook behavior. 

Having written that out, I'm leaning towards major bump. Other thoughts?

**Comment by majormoses** [comment]
definitely understand the conflict, I would however say that it does merit a major version bump to prevent it from breaking existing installs.

**Comment by scalp42** [comment]
yes, major bump please :warning:

**Comment by luckymike** [comment]
:+1:
