### ISSUE TITLE
redis from source

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-chef#340]
Right now this cookbook uses a redis recipe which builds redis from source. Why is that?

Every modern linux distribution like ubuntu, centos contains a redis package. Using the default package would allow to use the security patches of the distribution and reduce the install complexity.

This was already posted here but belongs to sensu-chef more than to chef-monitor...
https://github.com/portertech/chef-monitor/issues/33

**Comment by runningman84** [comment]
A redis installation can be a sample as this:
```
package "redis-server" do
  action :install
end

service "redis-server" do
  action [ :enable, :start ]
end
```

**Comment by portertech** [comment]
@runningman84 Redis from source is for consistency and it ensures a recent version installed that works with Sensu and the Redis configuration can be successfully managed by the cookbook (new options etc). We can certainly have another pass at it and see if things have changed.

**Comment by spuder** [comment]
Agreed, the version of redis in ubuntu 14.04 and centos 6 is very out of date.

**Comment by cwjohnston** [comment]
@portertech any thoughts on this as of now? I believe the instructions on sensuapp.org specify to install Redis (>= 1.3.14) via distro packages.

**Comment by cwjohnston** [comment]
I'm closing this as something we won't fix. The `redis` recipe in this cookbook is provided as a convenience; those who wish to install Redis from packages will be better served by providing a simple recipe in their organization's wrapper cookbook.
