### ISSUE TITLE
/etc/sensu/config.json got extra items from data bag 

### ISSUE THREAD

**Issue by autumnw** [sensu/sensu-chef#345]
Hi there,

If I put the rabbitmq password into databag item config.json as the following:
{
	"id" : "config",
	"rabbitmq" : {
		"password" : "sensutest01"
	}
}

I always got the extra attribute "id": "config" in "/etc/sensu/config.json".

**Comment by portertech** [comment]
We need to scrub the id from the hash before merging.

**Comment by cwjohnston** [comment]
Looks like this may still be a problem, can't see where we would currently be scrubbing the id before merging.
