### ISSUE TITLE
Add the ability to install a gem from a local file in sensu_gem LWRP

### ISSUE THREAD

**Issue by pmvilaca** [sensu/sensu-chef#352]
I was trying to fix an issue in a existing plugin and after building the new version (a new gem) I would like to copy the file to a cookbook and tell chef to install that gem from a local file, like what is described in the chef docs for the gem resource

```ruby
gem_package "right_aws" do
  source "/tmp/right_aws-1.11.0.gem"
  action :install
end
```
https://docs.chef.io/resource_gem_package.html

Probably, it isn't a very common use case for most of the users, but I think that it can be useful.

**Comment by obazoud** [comment]
+1
or install from github

**Comment by cwjohnston** [comment]
Added in #408 which will be part of the next release.
