### ISSUE TITLE
Sensu Client and Check Delete Actions

### ISSUE THREAD

**Issue by jhsubscribe** [sensu/sensu-chef#358]
G'day All,

This "Issue" is to discuss the best design for allowing client and check delete actions to be called.  I'm happy to attempt coding the pull request when I get time but wanted to verify the design first.   All suggestions welcome.... or it might take someone less time to implement than read this ;)

Our Scenario:
We have a wrapper cookbook (mn_monitor) that has "client" and "check" LWRPs that call sensu_client and sensu_check.   This works fine as long as you always call sensu_client create before any sensu_check create or deletes.    

In the event you want to remove monitoring, because sensu_client doesn't support delete, mn_monitor_client delete just stops the service and removes package.    However, if you run sensu_check delete in this scenario it then fails the chef run when it tries to notify the sensu_service_trigger as it's not defined in the resources collection

 [2015-07-07T15:21:25-07:00] FATAL: Chef::Exceptions::ResourceNotFound: resource file[C:\etc\sensu/conf.d/checks/*****.json] is configured to notify resource ruby_block[sensu_service_trigger] with action create, but ruby_block[sensu_service_trigger] cannot be found in the resource collection. 

My temporary hack is to only run deletes if the sensu_client is installed...
def delete_check
  sensu_check new_resource.check_name do
    action :delete
    only_if { run_context.resource_collection.include?("ruby_block[sensu_service_trigger]") }
  end
end

So the question is:
1) Is there a better way than my hack to modify sensu_check delete so that it only tries to restart the service if it exists?
2) Is there a better way to implement sensu_client delete than a service stop and package delete? (or maybe that's a fine start for now and can be improved later)

**Comment by scalp42** [comment]
I'm running into the same issue.

Plan is:

- write a library to curl Sensu api if `node['sensu']['client']['delete']` is set to `true`
- have a ternary operator on `sensu_client` action ( `action node['sensu']['client']['delete'] ? :nothing : :create`)

Then if you really want, you can add another logic to nuke everything (which is what you want I believe).

**Comment by cwjohnston** [comment]
Closing as I believe this issue has been addressed circa https://github.com/sensu/sensu-chef/commit/f55b87f0f07bb9e718262d5a1da2c2a5bf6db9d3. Please feel free to open a new issue if you are still experiencing problems.
