### ISSUE TITLE
Support for multiple brokers

### ISSUE THREAD

**Issue by maoe** [sensu/sensu-chef#363]
As far as I know, Sensu got a support for multiple RabbitMQ brokers as of v0.15 but there's no support in this cookbook.  Is there any plan to support it?

At a quick glance, the main problem is that it's a bit hard to make it backward compatible and it complicates the recipe(s) and attributes a bit. For example:

* `node.sensu.rabbitmq` probably should have `hosts` attribute that contains a `Mesh` or an `Array` of the information of RabbitMQ nodes.
* It does complicates the `rabbitmq` recipe. How do we find the appropriate host info (with ssl info) when applying the recipe?
    * One possible way is to assume we don't use multiple RabbitMQ instances on a host and use a `Mesh` with hostname as the keys in `node.sensu.rabbitmq.hosts`. We can look up the hostname from the Mesh for the ssl info then set up the instance.

What do you think?

**Comment by portertech** [comment]
@maoe You can currently use the `sensu_snippet` resource to create a "rabbitmq" snippet, containing an array of RabbitMQ broker connection hashes. :+1: 

We certainly need to revisit this cookbook tho.

**Comment by maoe** [comment]
Ah, I see. Thanks. I'll give it a try.

**Comment by maoe** [comment]
Fantastic! Thanks.
