### ISSUE TITLE
new chef-vault version 1.3.1 breaks library extension of ChefVaultItem

### ISSUE THREAD

**Issue by jklare** [sensu/sensu-chef#375]
Hi,

the recent release of the chef-vault cookbook 1.3.1 breaks the library extension in this cookbook for ChefVaultItem, since this module was removes/renamed/refactored. It is now called ChefVaultCookbook. I will push 2 pull requests for this issue to first fix this for the current stable release of this cookbook and then fix it for the next upcoming release.

Cheers,
Jan

**Comment by stevenolen** [comment]
This left my chef run in a bit of an issue because of https://github.com/chef-cookbooks/chef-vault/issues/41 and chef 11

Sticking to `chef-vault,'=1.3.0'` and `sensu,'=2.9.0'` seems to have helped until that issue is fixed..

**Comment by cwjohnston** [comment]
Closing as it appears this is fixed circa https://github.com/sensu/sensu-chef/commit/bdb34677daf189372b94784835a5c6f86a255578
