### ISSUE TITLE
sensu-chef 2.11.0 release?

### ISSUE THREAD

**Issue by martinisoft** [sensu/sensu-chef#385]
Would love to see a 2.11.0 release some time soon as it's been 5 months since the last version change. There is currently missing 2.10.0 CHANGELOG notes as mentioned in #360 as well.

**Comment by portertech** [comment]
@martinisoft org member invite sent!

**Comment by martinisoft** [comment]
Thank you @portertech I am prepping it now with e49c295be94e5cfc3a51f90830142c054ac9e100
