### ISSUE TITLE
Installation fails on redisio.

### ISSUE THREAD

**Issue by kplimack** [sensu/sensu-chef#394]
Redisio is attempting to make the user resource idempotent and is causing `sensu::redis` to fail.
https://github.com/brianbianco/redisio/issues/252

**Comment by cwjohnston** [comment]
Per the readme:
```
This cookbook provides the building blocks for creating a monitoring cookbook specific to your environment (wrapper). 
```

Closing as this appears to be an upstream issue in redisio that can be addressed by pinning redisio version in your wrapper cookbook.
