### ISSUE TITLE
Expose 'redact' array via LWRP

### ISSUE THREAD

**Issue by luckymike** [sensu/sensu-chef#395]
Add an explicit method to update the `redact` array in the client config to clearly provide a mechanism to redact additional client attributes.

**Comment by cwjohnston** [comment]
Originally I considered this a good possible addition, but as I consider this now it seems like we'll always be adding new attributes to this provider unless we adopt a guideline on this. 

I think it makes sense for optional attributes, like `redact`, to continue to be configured via the `additional` attribute. Although I recognize that the currently supported `keepalive` attribute doesn't conform to this rule, I would make an exception in that case.

**Comment by portertech** [comment]
@cwjohnston I recall giving a +1 for the addition of LWRP attributes when they are in Sensu Core, making `additional` for custom client definition attributes or those we have yet to add to the LWRP.
