### ISSUE TITLE
Installing .NET 3.5 fails on Windows 8.1

### ISSUE THREAD

**Issue by FreakyDug** [sensu/sensu-chef#397]
The Windows cookbook's version library, which is used to detect Windows Server 2012 so that the right .NET package is installed, misclassifies Windows 8.1. This causes the sensu cookbook to try and install NetFx3ServerFeatures rather than NetFx3, which fails.

I have raised an issue with the windows cookbook here: https://github.com/chef-cookbooks/windows/issues/335

**Comment by cwjohnston** [comment]
Closing as this appears to be an issue that needs to be fixed upstream in the windows cookbook.

**Comment by FreakyDug** [comment]
According to them (https://github.com/chef-cookbooks/windows/issues/335#issuecomment-178975137) sensu-chef should be using [Chef::ReservedNames::Win32::Version](https://github.com/chef/chef/blob/master/lib/chef/win32/version.rb) instead of the out of date windows cookbook library.

**Comment by cwjohnston** [comment]
@FreakyDug thanks for alerting us to the action item there. Reopening so we can look at fixing this for a future release.

**Comment by cwjohnston** [comment]
I believe this is fixed by #418 which will be released in upcoming version 2.12.0. Thanks!

**Comment by FreakyDug** [comment]
Yes, that fixed the problem. Thanks!
