### ISSUE TITLE
Apt-get won't run successfully in the vagrant example.

### ISSUE THREAD

**Issue by empath** [sensu/sensu-chef#398]
Errors like this for many, many packages.. 

==> default: Failed to fetch http://security.ubuntu.com/ubuntu/dists/raring-security/main/source/Sources  404  Not Found [IP: 91.189.91.14 80]

I tried with different versions of the opscode cookbook and none of them spun up.  I switched to the Precise 64 vagrant box and it seemed to work, though.

**Comment by cwjohnston** [comment]
Appears this may be a bug in the `examples/Vagrantfile` chef install script, in which `apt-get update` won't be run if `/opt/chef` directory already exists. We should probably run `apt-get update` regardless so as to increase the likelihood of successfully installing packages we depend on.

**Comment by cwjohnston** [comment]
We're removing the `Vagrantfile` setup from our examples, as we are maintaining test-kitchen suites with similar configurations.
