### ISSUE TITLE
Add support for pager_team to checks

### ISSUE THREAD

**Issue by rambler** [sensu/sensu-chef#399]
Checks can be configured with a `pager_team` attribute as per [the source](https://github.com/sensu/sensu-community-plugins/blob/master/handlers/notification/pagerduty.rb#L32).

Chef's check provider should accept that attribute as well.

**Comment by cwjohnston** [comment]
Because check configuration can contain an arbitrary number of keys, this may or may not be added in the future as an enhancement.

In the meantime, in case you are not aware, you can pass the `pager_team` as part of the value for the `additional` parameter on a `sensu_lwrp` check.

**Comment by cwjohnston** [comment]
Although `pager_team` may be used by many, it's not currently one of the attributes defined in the [check result specification](https://sensuapp.org/docs/latest/reference/checks.html#check-result-specification). 

Until such time as it is added to the check result specification, I'm 👎  on treating `pager_team` as a first-class attribute of `sensu_check` resources.
