### ISSUE TITLE
Add support for installing erlang via Erlang Solutions repositories

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-chef#411]
Sensu documentation [outlines installation of Erlang from the packages provided by Erlang Solutions](https://sensuapp.org/docs/0.21/install-rabbitmq). This cookbook should probably do the same.

**Comment by luckymike** [comment]
This ought to help out with the centos suites, I got this running enterprise-centos-65:

```
=INFO REPORT==== 2-Mar-2016::18:39:56 ===
started TCP Listener on [::]:5672

=ERROR REPORT==== 2-Mar-2016::18:39:56 ===
The installed version of Erlang (R14B04) contains the bug OTP-10905,
which makes it impossible to disable SSLv3. This makes the system
vulnerable to the POODLE attack. SSL listeners for AMQP have therefore
been disabled.
```

**Comment by cwjohnston** [comment]
Upon further review, it looks like we're already forcing use of ESL repos on Ubuntu <= 12.04 https://github.com/sensu/sensu-chef/blob/develop/recipes/rabbitmq.rb#L76-L80

**Comment by portertech** [comment]
@cwjohnston we should probably always use ESL and the nox proxy package.
