### ISSUE TITLE
Join Chef Partner Cookbook program

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-chef#430]
Chef has [announced](https://www.chef.io/blog/2016/02/23/chef-launches-partner-cookbook-program-to-expand-devops-ready-technology-ecosystem/) a [Partner Cookbook program](https://github.com/chef-partners/cookbook-guide) and we'd like this cookbook to be certified(?) under this program.

**Comment by cwjohnston** [comment]
Per the cookbook-guide presentation, I've emailed partnereng@chef.io for more information.

**Comment by jjasghar** [comment]
:metal:
