### ISSUE TITLE
Would like to see SmartOS/Solaris compatibility in this cookbook! 

### ISSUE THREAD

**Issue by joshzitting** [sensu/sensu-chef#436]
Let me know your thoughts/plans on that? According to [this](https://sensuapp.org/docs/0.23/sensu-on-oracle-solaris) ... Package support is coming soon for sensu and solaris.. 
Let me know if there is anything I can do!

**Comment by cwjohnston** [comment]
Thanks for offering your help @joshzitting! As I use SmartOS at home I am also interested in adding support for it in this cookbook, so I'm marking this as an enhancement and we'll assign it to a milestone as we get closer to usable packages for the platform.

**Comment by joshzitting** [comment]
smartos is a dying project. I dont think we need this anymore. Ill close it.
