### ISSUE TITLE
Provider json_file.rb creates directories with perms 0750 disregarding directory-mode attribute

### ISSUE THREAD

**Issue by kevins9** [sensu/sensu-chef#451]
## Expected Behavior
I expect new configuration directories to be created with the value of node["sensu"]["directory-mode"].

## Current Behavior
In file providers/json_file.rb line 11, directories are created explicitly with mode 0750, and not with the value of node["sensu"]["directory-mode"].

## Possible Solution
Change "mode 0750" to "mode node['sensu']['directory-mode']" in providers/json_file.rb.

## Steps to Reproduce (for bugs)
1.  Set node['sensu']['directory-mode'] to 0755.
2.  Run sensu::default.  Observe that /etc/sensu is created with permissions 0750.  Subdirectories of /etc/sensu, such as /etc/sensu/plugins, are set with 0755, honoring node['sensu']['directory-mode'].

## Context
I have a check that runs "sudo -u nonrootuser /etc/sensu/plugins/some-script.sh" and it fails because nonrootuser doesn't have rx on a path component (/etc/sensu) even though /etc/sensu/plugins has the correct permissions (I set node["sensu"]["directory-mode"] = 0755 in my wrapper, and that folder is created in recipes/default.rb line 47 using that attribute for the mode.) I am left with the choice to monkey patch providers/json_file.rb to use the attribute, change the permissions later on /etc/sensu and worry that a future invocation of chef-client could change it back, or add nonrootuser to the sensu group. Any ideas here on what's most appropriate/if json_file.rb is perhaps misguided in its assumptions?  (I worked around the problem with the third solution, adding 
nonrootuser to the sensu group.)

I see that this was last changed in the following commit: https://github.com/sensu/sensu-chef/commit/85b757468836b2f00034ae920a7bbf928707cb45
for the purposes of tightening up security. But I don't believe directory listings contain sensitive information, only files, and those files can be created with appropriate permissions if they contain sensitive information.  Feel free to close this issue if you disagree with me that this is an appropriate change.

## Your Environment
* Version of this cookbook used: 2.12.0
* Version of Sensu used: 0.22.0-1
* Version of Chef used: 12.8.1
* Operating System and version (e.g. CentOS 7, Ubuntu 14.04): CentOS 7.2.1511
* Link to your project: n/a

**Comment by cwjohnston** [comment]
Hi @kevins9, thanks for opening this issue. Would you care to review #472 and share your thoughts?

**Comment by kevins9** [comment]
@cwjohnston Looks good to me - thanks!
