### ISSUE TITLE
Support for multiple aggregate groups per check and named aggregates

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-chef#465]
As outlined here the chef lwrp does not support named aggregates or multiple aggregates yet:
https://github.com/sensu/sensu/pull/1379

A workaround is to use custom attributes...

**Comment by Evesy** [comment]
I believe [this PR](https://github.com/sensu/sensu-chef/pull/464) should be sufficient to get aggregates working again

**Comment by cwjohnston** [comment]
Closed by #464
