### ISSUE TITLE
sensu_check resource not working from Chef LWRP

### ISSUE THREAD

**Issue by thomasriley** [sensu/sensu-chef#467]
Hello. 

I have created a wrapper cookbook that builds and configures Sensu as required for our environment using chef-sensu. I created a LWRP resource named 'aggregate' which creates the required check files and it uses the sensu_check resource included in this cookbook.

However, I get this error when Chef calls the sensu_check resource:

`resource file[/etc/sensu/conf.d/checks/sensu_rabbitmq_node_health_aggregate.json] is configured to notify resource ruby_block[sensu_service_trigger] with action create, but ruby_block[sensu_service_trigger] cannot be found in the resource collection. file[/etc/sensu/conf.d/checks/sensu_rabbitmq_node_health_aggregate.json] is defined in /tmp/kitchen/cookbooks/sensu/providers/json_file.rb:14:in `block in class_from_file'`

If I include the sensu_check resource in a normal recipe it works perfectly fine.
The 'sensu::default' cookbook is included in the wrapper cookbook.

## Expected Behaviour
The sensu_check resource should work when calling from a LWRP resource.

## Current Behaviour
It fails to notify sensu_service_trigger, as per the error above.

## Steps to Reproduce (for bugs)
1. Include a sensu_check resource within a custom LWRP resource.
2. Then call your custom LWRP resource within a recipe in the wrapper cookbook.

## Context
Writing a cookbook that wraps chef-sensu and deploys check configuration files that are specific to our requirements.

## Your Environment

* Version of this cookbook used: 2.12.0
* Version of Sensu used: 0.25.1-1
* Version of Chef used: 12.5.1
* Operating System and version (e.g. CentOS 7, Ubuntu 14.04): CentOS 7.2.1511

**Comment by cwjohnston** [comment]
Hi @thomasriley, thanks for opening this issue. I think this may be fixed by #468 which was part of the recent 3.0.0 release. If you are still seeing this behavior with version 3.0.0 or newer, will you please open a new issue to let us know?

Thanks!
