### ISSUE TITLE
Add SENSU_LOADED_TEMPFILE_DIR to sensu.default.erb

### ISSUE THREAD

**Issue by sean-kang** [sensu/sensu-chef#486]
Sensu stores sensu_server_loaded_files in /tmp directory by default and it causes silent failures of handlers. An environmental variable SENSU_LOADED_TEMPFILE_DIR was added to Sensu to provide a way to change the directory in order to fix the problem.

Below is the related topics.
https://github.com/sensu/sensu-settings/issues/21
https://github.com/sensu/sensu-settings/pull/20

For example, adding the following line to /etc/default/sensu will fix the problem in Ubuntu 14.04.
export SENSU_LOADED_TEMPFILE_DIR=/var/run/sensu

My environment:
Ubuntu 14.04 LTS
Sensu 0.25.3-1
Chef 12.7.2-1

**Comment by cwjohnston** [comment]
Closed by #487
