### ISSUE TITLE
include_recipe "sensu::_enterprise_repo.rb"

### ISSUE THREAD

**Issue by garep** [sensu/sensu-chef#488]
Incorrect calling of recipe:
include_recipe "sensu::_enterprise_repo.rb"

Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/sensu/recipes/enterprise_dashboard.rb:
  
   13:  # Unless required by applicable law or agreed to in writing, software
   14:  # distributed under the License is distributed on an "AS IS" BASIS,
   15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   16:  # See the License for the specific language governing permissions and
   17:  # limitations under the License.
   18:  #
   19:  
   20>> include_recipe "sensu::_enterprise_repo.rb"
   21:  
   22:  package "sensu-enterprise-dashboard" do
   23:    version node["sensu"]["enterprise-dashboard"]["version"]
   24:  end
   25:  
   26:  sensu_dashboard_config node.name
   27:  

* Version of Sensu used: Current
* Version of Chef used: 12.11.18
* Operating System and version (e.g. CentOS 7, Ubuntu 14.04): Ubuntu 14.04
* Link to your project: GE Digital

**Comment by cwjohnston** [comment]
Closed by #499
