### ISSUE TITLE
Error in _linux.rb: undefined method `url' for Chef::Resource::YumRepository

### ISSUE THREAD

**Issue by kpmueller** [sensu/sensu-chef#495]
When running on a Centos6 node with the latest sensu recipe, it has a compile error.
  
## Expected Behavior

The recipe (sensu on linux) should run successfully.

## Current Behavior

================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/role_old_app/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `url' for Chef::Resource::YumRepository

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/sensu/recipes/_linux.rb:51:in `block in from_file'
    /var/chef/cache/cookbooks/sensu/recipes/_linux.rb:48:in `from_file'
    /var/chef/cache/cookbooks/sensu/recipes/default.rb:31:in `from_file'
    /var/chef/cache/cookbooks/piazza_base/recipes/_sensu.rb:2:in `from_file'
    /var/chef/cache/cookbooks/piazza_base/recipes/default.rb:29:in `from_file'
    /var/chef/cache/cookbooks/role_old_app/recipes/default.rb:1:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/sensu/recipes/_linux.rb:

   44:      options package_options
   45:      notifies :create, "ruby_block[sensu_service_trigger]"
   46:    end
   47:  when "rhel", "fedora"
   48:    repo = yum_repository "sensu" do
   49:      description "sensu monitoring"
   50:      repo = node["sensu"]["use_unstable_repo"] ? "yum-unstable" : "yum"
   51>>     url "#{node['sensu']['yum_repo_url']}/#{repo}/$basearch/"
   52:      action :add
   53:      only_if { node["sensu"]["add_repo"] }
   54:    end
   55:    repo.gpgcheck(false) if repo.respond_to?(:gpgcheck)

## Steps to Reproduce (for bugs)

the code is simply

include_recipe 'sensu'

## Context

Chef will not run successfully with sensu in it. :( 

## Your Environment

* Version of this cookbook used: sensu (3.0.0)
* Version of Sensu used: sensu-0.25.6-1.x86_64
* Version of Chef used: chef-12.14.60-1.el6.x86_64
* Operating System and version (e.g. CentOS 7, Ubuntu 14.04): Amazon Linux AMI release 2012.09

**Comment by kpmueller** [comment]
It looks like this is part of a change from yum cookbook going from 2.x to 3.x.

There appears to be a url -> baseurl alias, but I'm not sure why it's not working in this instance

**Comment by cwjohnston** [comment]
@kpmueller I believe this relates to https://github.com/chef/chef/issues/5317

My read is that `url` property was deprecated but no warnings about the deprecation were being logged. Looks like #494 will resolve this, but it's also been addressed on upstream master by Chef.

**Comment by kpmueller** [comment]
Great! Yeah, I think you're right. I'll try the monkey patch until 3.1.0 is released

**Comment by kpmueller** [comment]
The monkey patch reference in the Chef 12.14 issue works (adding to a libraries/default.rb in a cookbook)
