### ISSUE TITLE
Failing build in CPCP

### ISSUE THREAD

**Issue by jjasghar** [sensu/sensu-chef#513]
Looks like you have a failing build on master.

https://jenkins-01.eastus.cloudapp.azure.com/job/sensu-cookbook/lastFailedBuild/console

/cc @russellseymour

**Comment by cwjohnston** [comment]
Not sure what to make of this, but the failing gem (octokit 4.4.1) does seem to be available on rubygems (see https://rubygems.org/gems/octokit/versions/4.4.1)

**Comment by jjasghar** [comment]
Any chance you know where octokit is being pulled in from? I think it might be "emeril" but not 100% sure.

**Comment by cwjohnston** [comment]
Per my local Gemfile.lock it appears to be a dependency of berkshelf.

**Comment by cwjohnston** [comment]
Looks like most [recent builds](https://jenkins-01.eastus.cloudapp.azure.com/job/sensu-cookbook/135) are passing so I'm going to go ahead and close this issue.
