### ISSUE TITLE
init_style "runit" should be deprecated

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-chef#515]
## Expected Behavior

As described in https://github.com/sensu/sensu-omnibus/issues/34, the embedded runit service supervisor will be removed in Sensu 0.27. In accordance with this change, we should print deprecation warnings when "runit" is specified as the value of the `init_style` attribute.

## Current Behavior

Using this cookbook to configure the embedded runit supervisor does not produce warnings.

## Possible Solution

Implement log messages in `sensu_service` provider near [this line](https://github.com/sensu/sensu-chef/blob/fb2309a12cab21e456f24d5768424ed66012957b/providers/service.rb#L77), indicating that the "runit" provider is deprecated and will be removed in Sensu 0.27 and a subsequent version of this cookbook.

## Context

See https://github.com/sensu/sensu-omnibus/issues/34 for context around the changes to Sensu service management on Linux.

**Comment by tas50** [comment]
Doing a happy dance here
