### ISSUE TITLE
add support upstart and systemd

### ISSUE THREAD

**Issue by axos88** [sensu/sensu-chef#521]

**Comment by cwjohnston** [comment]
Hi @axos88, thanks for opening this issue. I recommend that you check out the proposed changes described in https://github.com/sensu/sensu-omnibus/issues/34. The short version is that the unsupported upstart scripts and the embedded runit service supervisor are going away in Sensu 0.27, to be replaced with official support for systemd and continued support for sysv init scripts.

As a result, we won't be adding upstart support, but will be adding logic to support systemd in this cookbook. I have opened https://github.com/sensu/sensu-chef/issues/522 to track that work.

**Comment by axos88** [comment]
awesome, thanks.
