### ISSUE TITLE
Support for init _style attribute in sensu_service resources should be removed 

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-chef#530]
## Expected Behavior

The cookbook should not claim to support service supervisors which are no longer supported by the underlying Sensu package.

## Current Behavior

The cookbook supports `runit` init style which is being removed from Sensu packages as of the 0.27 release. 

As of this writing `sysv` is the only other supported init service. 

Adding `systemd` to complement `sysv` doesn't quite fit, as only one set of service management files will be available on any given system installed from packages.

## Possible Solution

As Sensu 0.27 packages will be shipped per-platform-version, with sysv init or systemd unit files as appropriate, it might make sense to remove the `init_style` attribute from `sensu_service` all together.

**Comment by portertech** [comment]
I think it should be removed once the default release version is 0.27 :+1:
