### ISSUE TITLE
cant delete a check with out passing either subscribers or standalone

### ISSUE THREAD

**Issue by joshzitting** [sensu/sensu-chef#536]
https://github.com/sensu/sensu-chef/blob/develop/resources/check.rb#L30
This file will throw a fatal error if you just are specifying a check to delete without subcribers or standalone.. 

```
sensu_check "check_something" do
   action :delete
end
```
you have to specify subscribers or that the check is standalone to be able to delete it.. 

error code.. 
```Sensu check check_something: must either define subscribers, or has to be standalone.```

I think that to delete the check all you should have to specify is the name?

**Comment by cwjohnston** [comment]
Hi @joshzitting, thanks for reporting this issue. I've opened #538 to address it.
