### ISSUE TITLE
default.rb has a bug in master branch

### ISSUE THREAD

**Issue by yangyinying** [sensu/sensu-chef#561]
in master branch, file /recipes/default.rb line 96, it is:
if node["sensu"]["rabbitmq"].port == 5671

When running it, it raises an error complaining about no such function/method as "port". 

While in developer branch, it is correct:
if node["sensu"]["rabbitmq"]["port"] == 5671

Since the master branch is the one that will be included in the wrapper cookbook, it needs to be fixed.

Thanks.

**Comment by majormoses** [comment]
@cwjohnston where are you at with prepping for a release? If we are not close I am more than happy to submit a hotfix for it.

**Comment by salimkapadia** [comment]
@cwjohnston +1 bumping this. Do you have a release date ?

**Comment by cwjohnston** [comment]
4.0.2 was released to the supermarket today and includes this syntax fix for Chef 13 compatibility.
