### ISSUE TITLE
Add SLES support

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-chef#574]
## Expected Behavior
Install in SLES should work out of the box.

## Current Behavior
The cookbook does not allow sles right now.

## Possible Solution
Add support for SLES in https://github.com/sensu/sensu-chef/blob/develop/recipes/_linux.rb

## Steps to Reproduce (for bugs)
Use a SLES AMI like this 
suse-sles-12-sp2-v20161214-hvm-ssd-x86_64 (ami-9186a1e2) and use sensu-chef to install sensu.

## Context
The package itself supports SLES already:
https://github.com/sensu/sensu/issues/1666

## Your Environment
* Version of this cookbook used: any
* Version of Sensu used:  1.x
* Version of Chef used: 12.x
* Operating System and version (e.g. CentOS 7, Ubuntu 14.04): SLES 12

**Comment by majormoses** [comment]
Checking here: https://sensuapp.org/docs/1.0/platforms/ SUSE is not an officially supported platform. Regardless of whether sensu changes it's stance if we can support it I am :+1: could you please include a gist showing where it fails?

**Comment by majormoses** [comment]
closed via #576

**Comment by cwjohnston** [comment]
@runningman84 the intent of this cookbook's `yum_repo_releasever` attribute is to enable installations on RHEL derivative platforms like Amazon Linux and Suse. Please try setting the value of this attribute to `7` or whatever major version of RHEL is analagous to your version of SLES.
