### ISSUE TITLE
Cookbook does not support next generation Sensu (2.x)

### ISSUE THREAD

**Issue by thomasriley** [sensu/sensu-chef#588]
## Expected Behavior
This cookbook should be capable of installing the next generation version of Sensu (2.x)

## Current Behavior
The documentation for Sensu Alpha 2.x shows that the next generation of Sensu is quite different to 1.x in terms of architecture & installation process and this cookbook does not currently support this. 

## Possible Solution
Implement support for next generation by using the Sensu Alpha release. 

## Context
I would like to be able to install the Sensu Alpha using Chef.

**Comment by thomasriley** [comment]
I have got access to the Sensu Alpha so that I can look at supporting it via this cookbook.

**Comment by majormoses** [comment]
Cool, let's create an alpha branch and start from scratch.

**Comment by thomasriley** [comment]
As Ben says, the plan is to start a new alpha branch from scratch for developing the next gen version of this cookbook for Sensu 2.x.

Will initially support CentOS & Debian and branch out to other platforms as this work progresses.

**Comment by thomasriley** [comment]
Here is the branch I will be developing this on: https://github.com/sensu/sensu-chef/tree/next_gen

**Comment by majormoses** [comment]
so just realized this was still open see: https://github.com/sensu/sensu-go-chef for how to manage sensu-go with chef.
