### ISSUE TITLE
How do I add keys to a `sensu_check` resources that are not part of the spec?

### ISSUE THREAD

**Issue by jfineberg** [sensu/sensu-chef#622]
## Expected Behavior
I should be able to provide a contact name that has been defined in the "contacts" definition (Sensu Enterprise feature)

```
sensu_check "stats_check" do
  command "stats-check.py"
  handlers ["slack"]
  contact "dev"
  subscribers ["some_stats_subscriber"]
  interval 60
end
```

## Current Behavior
The `sensu_check` resource will throw an error with this unknown 'contact' attribute.

```
    sensu_check "stats_check" do
       command "stats-check.py"
       handlers ["slack"]
>>     contact "dev"
       subscribers ["some_stats_subscriber"]
       interval 60
    end
...
[2018-10-17T00:19:26+00:00] FATAL: NoMethodError: undefined method `contact' for Custom resource sensu_check from cookbook sensu
```

## Possible Solution
Allow a "contact" attribute in `sensu_check`.  Ideally, also provide a `sensu_contact` resource that puts JSON files in `node["sensu"]["directory"]/conf.d/contacts/`

## Context
My organization is using this Chef cookbook with Sensu Enterprise, and we have the need to add special Contact Routing for certain checks.  We can use `sensu_snippet` to generate the contacts JSON, but without the `sensu_check` resource supporting a contact name, it's quite troublesome to take full advantage of Sensu Enterprise and Contact Routing.

## Your Environment
* Version of this cookbook used: 5.4.0
* Version of Sensu used: Enterprise 3.2.2
* Version of Chef used: 14.0.190
* Operating System and version (e.g. CentOS 7, Ubuntu 14.04): Ubuntu 16.04.5 LTS (Xenial Xerus)
* Link to your project: https://whereto.com/

**Comment by majormoses** [comment]
@jfineberg you can use the `additional` hash to add arbitrary keys, see: https://github.com/sensu/sensu-chef#define-a-check or https://gist.github.com/majormoses/6b670730551bf59c60165b19a3afdefe for examples

**Comment by jfineberg** [comment]
Gosh, I don't know how I forgot about "additional" attributes.  Thanks, this is working well now.  Feel free to close the issue.
