### ISSUE TITLE
i want to create a document for chef14.

### ISSUE THREAD

**Issue by ajaydevops2019** [sensu/sensu-chef#625]
could you please help me. give me some points for upagrade chef14

**Comment by majormoses** [comment]
@ajaydevops2019 this cookbook already supports chef 14 and as I previously stated in https://github.com/sensu/sensu-chef/issues/605#issuecomment-464364907 without having access to your code I can only share generic resources as it depends on what cookbooks you are using. I am more than happy to discuss specific issues with this cookbook you may have with chef 14 but asking generically how to upgrade chef is well out of scope of any github issue and certainly not something that is specific to this repository or sensu.
